export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const RESET_BURGER_INGREDIENTS = "RESET_BURGER_INGREDIENTS";
export const SET_INGREDIENT_LIST_SUCCESS = "SET_INGREDIENT_LIST_SUCCESS";
export const SET_INGREDIENT_LIST_FAILED = "SET_INGREDIENT_LIST_FAILED";
